<a href="https://colab.research.google.com/github/udlbook/udlbook/blob/main/Notebooks/Chap12/12_1_Self_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Notebook 12.1: Self Attention**

This notebook builds a self-attention mechanism from scratch, as discussed in section 12.2 of the book.

Work through the cells below, running each cell in turn. In various places you will see the words "TO DO". Follow the instructions at these places and make predictions about what is going to happen or write code to complete the functions.

Contact me at udlbookmail@gmail.com if you find any mistakes or have any suggestions.



In [10]:
import math

import numpy as np
import matplotlib.pyplot as plt

The self-attention mechanism maps $N$ inputs $\mathbf{x}_{n}\in\mathbb{R}^{D}$ and returns $N$ outputs $\mathbf{x}'_{n}\in \mathbb{R}^{D}$.  



In [11]:
# Set seed so we get the same random numbers
np.random.seed(3)
# Number of inputs
N = 3
# Number of dimensions of each input
D = 4
# Create an empty list
all_x = []
# Create elements x_n and append to list
for n in range(N):
  all_x.append(np.random.normal(size=(D,1)))
# Print out the list
print(all_x)


[array([[ 1.78862847],
       [ 0.43650985],
       [ 0.09649747],
       [-1.8634927 ]]), array([[-0.2773882 ],
       [-0.35475898],
       [-0.08274148],
       [-0.62700068]]), array([[-0.04381817],
       [-0.47721803],
       [-1.31386475],
       [ 0.88462238]])]


We'll also need the weights and biases for the keys, queries, and values (equations 12.2 and 12.4)

In [12]:
# Set seed so we get the same random numbers
np.random.seed(0)

# Choose random values for the parameters
omega_q = np.random.normal(size=(D,D))
omega_k = np.random.normal(size=(D,D))
omega_v = np.random.normal(size=(D,D))
beta_q = np.random.normal(size=(D,1))
beta_k = np.random.normal(size=(D,1))
beta_v = np.random.normal(size=(D,1))

Now let's compute the queries, keys, and values for each input

In [13]:
# Make three lists to store queries, keys, and values
all_queries = []
all_keys = []
all_values = []
# For every input
for x in all_x:
  # TODO -- compute the keys, queries and values.
  # Replace these three lines
  #query = np.ones_like(x)
  #key = np.ones_like(x)
  #value = np.ones_like(x)
  query = beta_q + (np.matmul(omega_q, x))
  key = beta_k + (np.matmul(omega_k, x))
  value = beta_v + (np.matmul(omega_v, x))

  all_queries.append(query)
  all_keys.append(key)
  all_values.append(value)
print(np.array(all_values).shape)

(3, 4, 1)


We'll need a softmax function (equation 12.5) -- here, it will take a list of arbitrary numbers and return a list where the elements are non-negative and sum to one


In [14]:
def softmax(items_in):

  from functools import reduce
  import math

  # TODO Compute the elements of items_out
  # Replace this line
  #items_out = items_in.copy()
  denominator = reduce(lambda acc, item: acc + math.exp(item), items_in,0)
  items_out = [math.exp(item) / denominator for item in items_in]

  return np.array(items_out)

Now compute the self attention values:

In [15]:
# Create emptymlist for output
all_x_prime = []
# For each output
for n in range(N):
  # Create list for dot products of query N with all keys
  all_km_qn = []
  # Compute the dot products
  for key in all_keys:
    # TODO -- compute the appropriate dot product
    # Replace this line
    #dot_product = 1
    qn = all_queries[n]
    dot_product = np.dot(key.transpose(), qn)
    # Store dot product
    all_km_qn.append(dot_product)

  # Compute dot product
  attention = softmax(all_km_qn)
  # Print result (should be positive sum to one)
  print("Attentions for output ", n)
  print(attention)

  # TODO: Compute a weighted sum of all of the values according to the attention
  # (equation 12.3)
  # Replace this line
  #x_prime = np.zeros((D,1))
  x_prime = np.matmul(np.array(all_values).transpose(), attention)
  all_x_prime.append(x_prime)


# Print out true values to check you have it correct
print("x_prime_0_calculated:", all_x_prime[0].transpose())
print("x_prime_0_true: [[ 0.94744244 -0.24348429 -0.91310441 -0.44522983]]")
print("x_prime_1_calculated:", all_x_prime[1].transpose())
print("x_prime_1_true: [[ 1.64201168 -0.08470004  4.02764044  2.18690791]]")
print("x_prime_2_calculated:", all_x_prime[2].transpose())
print("x_prime_2_true: [[ 1.61949281 -0.06641533  3.96863308  2.15858316]]")


Attentions for output  0
[1.24326146e-13 9.98281489e-01 1.71851130e-03]
Attentions for output  1
[2.79525306e-12 5.85506360e-03 9.94144936e-01]
Attentions for output  2
[0.00505708 0.00654776 0.98839516]
x_prime_0_calculated: [[ 0.94744244]
 [-0.24348429]
 [-0.91310441]
 [-0.44522983]]
x_prime_0_true: [[ 0.94744244 -0.24348429 -0.91310441 -0.44522983]]
x_prime_1_calculated: [[ 1.64201168]
 [-0.08470004]
 [ 4.02764044]
 [ 2.18690791]]
x_prime_1_true: [[ 1.64201168 -0.08470004  4.02764044  2.18690791]]
x_prime_2_calculated: [[ 1.61949281]
 [-0.06641533]
 [ 3.96863308]
 [ 2.15858316]]
x_prime_2_true: [[ 1.61949281 -0.06641533  3.96863308  2.15858316]]


/var/folders/cv/z7xz0c3n3nd4c26hj7g01n7w0000gn/T/ipykernel_34596/761054674.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  denominator = reduce(lambda acc, item: acc + math.exp(item), items_in,0)
/var/folders/cv/z7xz0c3n3nd4c26hj7g01n7w0000gn/T/ipykernel_34596/761054674.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  items_out = [math.exp(item) / denominator for item in items_in]


Now let's compute the same thing, but using matrix calculations.  We'll store the $N$ inputs $\mathbf{x}_{n}\in\mathbb{R}^{D}$ in the columns of a $D\times N$ matrix, using equations 12.6 and 12.7/8.

Note:  The book uses column vectors (for compatibility with the rest of the text), but in the wider literature it is more normal to store the inputs in the rows of a matrix;  in this case, the computation is the same, but all the matrices are transposed and the operations proceed in the reverse order.

In [16]:
# Define softmax operation that works independently on each column
def softmax_cols(data_in):
  # Exponentiate all of the values
  exp_values = np.exp(data_in) ;
  # Sum over columns
  denom = np.sum(exp_values, axis = 0);
  # Replicate denominator to N rows
  denom = np.matmul(np.ones((data_in.shape[0],1)), denom[np.newaxis,:])
  # Compute softmax
  softmax = exp_values / denom
  # return the answer
  return softmax

In [56]:
#Now let's compute self attention in matrix form
def compute_q_k_v(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k):
  queries_X = np.matmul(beta_q, np.ones((N,1)).transpose()) + np.matmul(omega_q, X)
  keys_X = np.matmul(beta_k, np.ones((N,1)).transpose()) + np.matmul(omega_k, X)
  values_X = np.matmul(beta_v, np.ones((N,1)).transpose()) + np.matmul(omega_v, X)
  return queries_X, keys_X, values_X

def compute_dot_products(keys_X, queries_X):
    #dot product is key transposed * query
    dot_products = np.matmul(keys_X.transpose(), queries_X)
    return dot_products

def weight_values_by_attention(values_X, dot_products_softmax):
    X_prime = np.matmul(values_X, dot_products_softmax)
    return X_prime

def self_attention(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k):

  # TODO -- Write this function
  # 1. Compute queries, keys, and values
  queries_X, keys_X, values_X = compute_q_k_v(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k)
  #2. Compute dot products
  dot_products = compute_dot_products(keys_X, queries_X)
  #3. Apply softmax to calculate attentions
  dot_products_softmax = softmax_cols(dot_products)
  print("attention matrix:\n" + str(dot_products_softmax))
  # 4. Weight values by attentions
  X_prime = weight_values_by_attention(values_X, dot_products_softmax)
  # Replace this line
  #X_prime = np.zeros_like(X)

  return X_prime

In [57]:
# Copy data into matrix
X = np.zeros((D, N))
X[:,0] = np.squeeze(all_x[0])
X[:,1] = np.squeeze(all_x[1])
X[:,2] = np.squeeze(all_x[2])

# Run the self attention mechanism
X_prime = self_attention(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k)

# Print out the results
print(X_prime)

attention matrix:
[[1.24326146e-13 2.79525306e-12 5.05707907e-03]
 [9.98281489e-01 5.85506360e-03 6.54776072e-03]
 [1.71851130e-03 9.94144936e-01 9.88395160e-01]]
[[ 0.94744244  1.64201168  1.61949281]
 [-0.24348429 -0.08470004 -0.06641533]
 [-0.91310441  4.02764044  3.96863308]
 [-0.44522983  2.18690791  2.15858316]]


If you did this correctly, the values should be the same as above.

TODO:  

Print out the attention matrix
You will see that the values are quite extreme (one is very close to one and the others are very close to zero.  Now we'll fix this problem by using scaled dot-product attention.

In [58]:
# Now let's compute self attention in matrix form
def scaled_dot_product_self_attention(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k):

  # TODO -- Write this function
  # 1. Compute queries, keys, and values
  queries_X, keys_X, values_X = compute_q_k_v(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k)
  # 2. Compute dot products
  dot_products = compute_dot_products(keys_X, queries_X)
  # 3. Scale the dot products as in equation 12.9
  dot_products_scaled = dot_products / math.sqrt(D)
  # 4. Apply softmax to calculate attentions
  dot_products_softmax =  softmax_cols(dot_products_scaled)
  # 5. Weight values by attentions
  X_prime = weight_values_by_attention(values_X, dot_products_softmax)
  # Replace this line
  #X_prime = np.zeros_like(X);

  return X_prime

In [59]:
# Run the self attention mechanism
X_prime = scaled_dot_product_self_attention(X,omega_v, omega_q, omega_k, beta_v, beta_q, beta_k)

# Print out the results
print(X_prime)

[[ 0.97411966  1.59622051  1.32638014]
 [-0.23738409 -0.09516106  0.13062402]
 [-0.72333202  3.70194096  3.02371664]
 [-0.34413007  2.01339538  1.6902419 ]]


TODO -- Investigate whether the self-attention mechanism is covariant with respect to permutation.
If it is, when we permute the columns of the input matrix $\mathbf{X}$, the columns of the output matrix $\mathbf{X}'$ will also be permuted.
